name: ase-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - numpy
  - scipy
  - pandas
  - ase
  - matplotlib
  - pip
  - python=3.9
  - python-language-server
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  # - numba
  # - bokeh
  # - captum
  # - cudatoolkit=11.1
  # - datashader
  # - gh
  # - git
  # - holoviews
  # - hvplot
  # - ipywidgets
  # - optuna
  # - panel
  # - pip:
  #   - -r requirements.txt
  # - pyarrow
  # - pytorch=1.9
  # - pytorch-lightning
  # - pyviz_comms
  # - scikit-learn
  # - tensorboard
  # - torchaudio
  # - torchmetrics
  # - torchtext
  # - torchvision
  # - wandb
  # - xeus-python
